### ISSUE TITLE
[BUG] Update the documentation gifs with the new site look'n'feel

### ISSUE THREAD

**Issue by vishalchangrani** [onflow/CAST#11]
**Describe the bug**
Cast was recently updated with a new look'n'feel. The color scheme has changed. The gifs in the documentation, however still reflect the old scheme.

**To Reproduce**
e.g. https://dapper-collectives-1.gitbook.io/cast-docs/getting-started#setting-up-a-community
There are a few of these gifs.

**Expected behavior**
The gif need to be updated with the latest screen capture.

**Screenshots**

**Comment by AmarildoGrembi** [comment]
All the gifs used currently:
- [x] https://dapper-collectives-1.gitbook.io/cast-docs/getting-started blocked by #4 
- [x] https://dapper-collectives-1.gitbook.io/cast-docs/getting-started#setting-up-a-community blocked by #10
- [x] https://dapper-collectives-1.gitbook.io/cast-docs/getting-started#drafting-a-proposal
- [x] https://dapper-collectives-1.gitbook.io/cast-docs/getting-started#canceling-a-proposal
- [x] https://dapper-collectives-1.gitbook.io/cast-docs/getting-started#voting-on-a-proposal
